export interface Drug {
  name: string;
  category: string;
  class: string;
  dosage: string;
  indications: string[];
  contraindications: string[];
  interactions: string[];
  sideEffects: string[];
  monitoring: string[];
  conditions: string[];
}

export const comprehensiveDrugs: Drug[] = [
  // ANALGESICS - Pain Relief (15+ drugs)
  {
    name: "Ibuprofen",
    category: "Analgesic",
    class: "NSAID",
    dosage: "200-800mg every 4-6 hours",
    indications: ["Pain relief", "Fever reduction", "Inflammation"],
    contraindications: ["Peptic ulcer", "Kidney disease", "Pregnancy (3rd trimester)"],
    interactions: ["Warfarin", "Aspirin", "ACE inhibitors"],
    sideEffects: ["Stomach upset", "Dizziness", "Rash"],
    monitoring: ["Renal function", "Liver function", "Blood pressure"],
    conditions: ["Pain", "Fever", "Inflammation", "Headache", "Muscle pain"]
  },
  {
    name: "Paracetamol",
    category: "Analgesic",
    class: "Acetaminophen",
    dosage: "500-1000mg every 4-6 hours",
    indications: ["Pain relief", "Fever reduction"],
    contraindications: ["Liver disease", "Alcohol abuse"],
    interactions: ["Warfarin", "Alcohol", "Other paracetamol products"],
    sideEffects: ["Liver damage (overdose)", "Allergic reactions"],
    monitoring: ["Liver function", "Daily dose limit"],
    conditions: ["Pain", "Fever", "Headache", "Toothache", "Menstrual pain"]
  },
  {
    name: "Morphine",
    category: "Analgesic",
    class: "Opioid",
    dosage: "5-30mg every 4 hours as needed",
    indications: ["Severe pain", "Post-operative pain", "Cancer pain"],
    contraindications: ["Respiratory depression", "Paralytic ileus", "Acute bronchial asthma"],
    interactions: ["Benzodiazepines", "Alcohol", "MAO inhibitors", "SSRIs"],
    sideEffects: ["Respiratory depression", "Sedation", "Constipation", "Nausea"],
    monitoring: ["Respiratory rate", "Pain level", "Mental status", "Bowel function"],
    conditions: ["Severe pain", "Post-operative pain", "Cancer pain", "Trauma pain"]
  },
  {
    name: "Tramadol",
    category: "Analgesic",
    class: "Opioid",
    dosage: "50-100mg every 4-6 hours",
    indications: ["Moderate to severe pain", "Chronic pain", "Post-operative pain"],
    contraindications: ["Respiratory depression", "Acute intoxication", "MAO inhibitors"],
    interactions: ["MAO inhibitors", "SSRIs", "Alcohol", "Benzodiazepines"],
    sideEffects: ["Dizziness", "Nausea", "Constipation", "Headache"],
    monitoring: ["Pain level", "Mental status", "Respiratory rate", "Bowel function"],
    conditions: ["Moderate pain", "Chronic pain", "Post-operative pain", "Back pain"]
  },
  {
    name: "Codeine",
    category: "Analgesic",
    class: "Opioid",
    dosage: "15-60mg every 4-6 hours",
    indications: ["Mild to moderate pain", "Cough suppression"],
    contraindications: ["Respiratory depression", "Acute bronchial asthma", "Paralytic ileus"],
    interactions: ["Alcohol", "Benzodiazepines", "MAO inhibitors", "SSRIs"],
    sideEffects: ["Drowsiness", "Constipation", "Nausea", "Respiratory depression"],
    monitoring: ["Pain level", "Respiratory rate", "Mental status", "Bowel function"],
    conditions: ["Mild pain", "Cough", "Post-operative pain", "Dental pain"]
  },
  {
    name: "Aspirin",
    category: "Analgesic",
    class: "Salicylate",
    dosage: "325-650mg every 4-6 hours",
    indications: ["Pain relief", "Fever reduction", "Cardiovascular protection"],
    contraindications: ["Peptic ulcer", "Bleeding disorders", "Pregnancy (3rd trimester)"],
    interactions: ["Warfarin", "NSAIDs", "ACE inhibitors", "Diuretics"],
    sideEffects: ["Stomach upset", "Bleeding", "Tinnitus", "Reye's syndrome"],
    monitoring: ["Bleeding time", "Stomach symptoms", "Hearing", "Liver function"],
    conditions: ["Pain", "Fever", "Cardiovascular protection", "Headache"]
  },
  {
    name: "Diclofenac",
    category: "Analgesic",
    class: "NSAID",
    dosage: "25-50mg 2-3 times daily",
    indications: ["Pain relief", "Inflammation", "Arthritis"],
    contraindications: ["Peptic ulcer", "Heart disease", "Kidney disease"],
    interactions: ["Warfarin", "Diuretics", "ACE inhibitors"],
    sideEffects: ["Stomach upset", "Dizziness", "Edema"],
    monitoring: ["Renal function", "Blood pressure", "Cardiac function"],
    conditions: ["Pain", "Inflammation", "Arthritis", "Muscle pain", "Joint pain"]
  },
  {
    name: "Naproxen",
    category: "Analgesic",
    class: "NSAID",
    dosage: "250-500mg twice daily",
    indications: ["Pain relief", "Inflammation", "Arthritis", "Dysmenorrhea"],
    contraindications: ["Peptic ulcer", "Heart disease", "Kidney disease"],
    interactions: ["Warfarin", "Lithium", "Methotrexate", "ACE inhibitors"],
    sideEffects: ["Stomach upset", "Drowsiness", "Edema", "Hypertension"],
    monitoring: ["Renal function", "Blood pressure", "Cardiac function"],
    conditions: ["Pain", "Inflammation", "Arthritis", "Menstrual pain", "Joint pain"]
  },
  {
    name: "Celecoxib",
    category: "Analgesic",
    class: "COX-2 Inhibitor",
    dosage: "100-200mg twice daily",
    indications: ["Osteoarthritis", "Rheumatoid arthritis", "Acute pain"],
    contraindications: ["Peptic ulcer", "Heart disease", "Kidney disease", "Sulfa allergy"],
    interactions: ["Warfarin", "ACE inhibitors", "Diuretics", "Lithium"],
    sideEffects: ["Stomach upset", "Dizziness", "Hypertension", "Edema"],
    monitoring: ["Cardiac function", "Blood pressure", "Renal function"],
    conditions: ["Pain", "Arthritis", "Joint pain", "Inflammation"]
  },
  {
    name: "Ketorolac",
    category: "Analgesic",
    class: "NSAID",
    dosage: "10mg every 4-6 hours (max 40mg/day)",
    indications: ["Moderate to severe pain", "Post-operative pain", "Migraine"],
    contraindications: ["Peptic ulcer", "Kidney disease", "Pregnancy", "Bleeding disorders"],
    interactions: ["Warfarin", "ACE inhibitors", "Diuretics", "Lithium"],
    sideEffects: ["Stomach upset", "Bleeding", "Kidney problems", "Dizziness"],
    monitoring: ["Renal function", "Bleeding time", "Stomach symptoms"],
    conditions: ["Moderate pain", "Post-operative pain", "Migraine", "Dental pain"]
  },
  {
    name: "Oxycodone",
    category: "Analgesic",
    class: "Opioid",
    dosage: "5-20mg every 4-6 hours",
    indications: ["Moderate to severe pain", "Chronic pain", "Cancer pain"],
    contraindications: ["Respiratory depression", "Acute bronchial asthma", "Paralytic ileus"],
    interactions: ["Alcohol", "Benzodiazepines", "MAO inhibitors", "SSRIs"],
    sideEffects: ["Respiratory depression", "Sedation", "Constipation", "Nausea"],
    monitoring: ["Respiratory rate", "Pain level", "Mental status", "Bowel function"],
    conditions: ["Moderate pain", "Chronic pain", "Cancer pain", "Post-operative pain"]
  },
  {
    name: "Hydrocodone",
    category: "Analgesic",
    class: "Opioid",
    dosage: "5-10mg every 4-6 hours",
    indications: ["Moderate to severe pain", "Cough suppression"],
    contraindications: ["Respiratory depression", "Acute bronchial asthma", "Paralytic ileus"],
    interactions: ["Alcohol", "Benzodiazepines", "MAO inhibitors", "SSRIs"],
    sideEffects: ["Drowsiness", "Constipation", "Nausea", "Respiratory depression"],
    monitoring: ["Pain level", "Respiratory rate", "Mental status", "Bowel function"],
    conditions: ["Moderate pain", "Cough", "Post-operative pain", "Chronic pain"]
  },
  {
    name: "Fentanyl",
    category: "Analgesic",
    class: "Opioid",
    dosage: "25-100mcg patch every 72 hours",
    indications: ["Severe chronic pain", "Cancer pain", "Breakthrough pain"],
    contraindications: ["Respiratory depression", "Acute pain", "Paralytic ileus"],
    interactions: ["Alcohol", "Benzodiazepines", "MAO inhibitors", "SSRIs"],
    sideEffects: ["Respiratory depression", "Sedation", "Constipation", "Nausea"],
    monitoring: ["Respiratory rate", "Pain level", "Mental status", "Bowel function"],
    conditions: ["Severe pain", "Chronic pain", "Cancer pain", "Breakthrough pain"]
  },
  {
    name: "Buprenorphine",
    category: "Analgesic",
    class: "Partial Opioid Agonist",
    dosage: "0.2-0.8mg every 6-8 hours",
    indications: ["Moderate to severe pain", "Opioid dependence", "Chronic pain"],
    contraindications: ["Respiratory depression", "Acute bronchial asthma", "Paralytic ileus"],
    interactions: ["Alcohol", "Benzodiazepines", "MAO inhibitors", "SSRIs"],
    sideEffects: ["Headache", "Nausea", "Constipation", "Insomnia"],
    monitoring: ["Pain level", "Mental status", "Bowel function", "Dependence"],
    conditions: ["Moderate pain", "Chronic pain", "Opioid dependence", "Post-operative pain"]
  },
  {
    name: "Tapentadol",
    category: "Analgesic",
    class: "Opioid + Norepinephrine Reuptake Inhibitor",
    dosage: "50-100mg every 4-6 hours",
    indications: ["Moderate to severe pain", "Chronic pain", "Neuropathic pain"],
    contraindications: ["Respiratory depression", "Acute bronchial asthma", "Paralytic ileus"],
    interactions: ["MAO inhibitors", "SSRIs", "Alcohol", "Benzodiazepines"],
    sideEffects: ["Nausea", "Dizziness", "Constipation", "Headache"],
    monitoring: ["Pain level", "Mental status", "Respiratory rate", "Bowel function"],
    conditions: ["Moderate pain", "Chronic pain", "Neuropathic pain", "Post-operative pain"]
  },

  // ANTI-INFLAMMATORY (15+ drugs)
  {
    name: "Prednisolone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "5-60mg daily (varies by condition)",
    indications: ["Inflammation", "Autoimmune conditions", "Allergic reactions"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Autoimmune conditions", "Allergies", "Asthma", "Arthritis"]
  },
  {
    name: "Methylprednisolone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "4-48mg daily (varies by condition)",
    indications: ["Inflammation", "Autoimmune conditions", "Acute exacerbations"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Autoimmune conditions", "Acute exacerbations", "Asthma"]
  },
  {
    name: "Dexamethasone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "0.5-10mg daily (varies by condition)",
    indications: ["Inflammation", "Allergic reactions", "Cerebral edema"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Allergies", "Cerebral edema", "Asthma", "Arthritis"]
  },
  {
    name: "Hydrocortisone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "20-240mg daily (varies by condition)",
    indications: ["Inflammation", "Adrenal insufficiency", "Allergic reactions"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Adrenal insufficiency", "Allergies", "Asthma"]
  },
  {
    name: "Betamethasone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "0.5-5mg daily (varies by condition)",
    indications: ["Inflammation", "Skin conditions", "Allergic reactions"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Skin conditions", "Allergies", "Asthma", "Arthritis"]
  },
  {
    name: "Triamcinolone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "4-48mg daily (varies by condition)",
    indications: ["Inflammation", "Allergic reactions", "Skin conditions"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Allergies", "Skin conditions", "Asthma", "Arthritis"]
  },
  {
    name: "Fludrocortisone",
    category: "Anti-inflammatory",
    class: "Mineralocorticoid",
    dosage: "0.05-0.2mg daily",
    indications: ["Adrenal insufficiency", "Orthostatic hypotension"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Edema", "Hypertension", "Hypokalemia", "Weight gain"],
    monitoring: ["Blood pressure", "Electrolytes", "Weight", "Edema"],
    conditions: ["Adrenal insufficiency", "Orthostatic hypotension", "Salt wasting"]
  },
  {
    name: "Cortisone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "25-300mg daily (varies by condition)",
    indications: ["Inflammation", "Adrenal insufficiency", "Allergic reactions"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Adrenal insufficiency", "Allergies", "Asthma"]
  },
  {
    name: "Prednisone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "5-60mg daily (varies by condition)",
    indications: ["Inflammation", "Autoimmune conditions", "Allergic reactions"],
    contraindications: ["Systemic fungal infection", "Live vaccines", "Peptic ulcer"],
    interactions: ["NSAIDs", "Warfarin", "Diuretics", "Antidiabetics"],
    sideEffects: ["Weight gain", "Osteoporosis", "Diabetes", "Hypertension"],
    monitoring: ["Blood glucose", "Blood pressure", "Bone density", "Electrolytes"],
    conditions: ["Inflammation", "Autoimmune conditions", "Allergies", "Asthma", "Arthritis"]
  },
  {
    name: "Budesonide",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "200-800mcg daily in divided doses",
    indications: ["Asthma", "COPD", "Allergic rhinitis"],
    contraindications: ["Hypersensitivity", "Active tuberculosis", "Untreated fungal infection"],
    interactions: ["Ketoconazole", "Ritonavir", "Grapefruit juice"],
    sideEffects: ["Oral candidiasis", "Hoarseness", "Cough", "Adrenal suppression"],
    monitoring: ["Peak flow", "Symptoms", "Oral examination", "Adrenal function"],
    conditions: ["Asthma", "COPD", "Allergic rhinitis", "Inflammation", "Allergies"]
  },
  {
    name: "Fluticasone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "100-500mcg daily in divided doses",
    indications: ["Asthma", "COPD", "Allergic rhinitis"],
    contraindications: ["Hypersensitivity", "Active tuberculosis", "Untreated fungal infection"],
    interactions: ["Ketoconazole", "Ritonavir", "Grapefruit juice"],
    sideEffects: ["Oral candidiasis", "Hoarseness", "Cough", "Adrenal suppression"],
    monitoring: ["Peak flow", "Symptoms", "Oral examination", "Adrenal function"],
    conditions: ["Asthma", "COPD", "Allergic rhinitis", "Inflammation", "Allergies"]
  },
  {
    name: "Mometasone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "200-400mcg daily in divided doses",
    indications: ["Asthma", "Allergic rhinitis", "Skin conditions"],
    contraindications: ["Hypersensitivity", "Active tuberculosis", "Untreated fungal infection"],
    interactions: ["Ketoconazole", "Ritonavir", "Grapefruit juice"],
    sideEffects: ["Oral candidiasis", "Hoarseness", "Cough", "Adrenal suppression"],
    monitoring: ["Peak flow", "Symptoms", "Oral examination", "Adrenal function"],
    conditions: ["Asthma", "Allergic rhinitis", "Skin conditions", "Inflammation", "Allergies"]
  },
  {
    name: "Beclomethasone",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "200-800mcg daily in divided doses",
    indications: ["Asthma", "Allergic rhinitis", "COPD"],
    contraindications: ["Hypersensitivity", "Active tuberculosis", "Untreated fungal infection"],
    interactions: ["Ketoconazole", "Ritonavir", "Grapefruit juice"],
    sideEffects: ["Oral candidiasis", "Hoarseness", "Cough", "Adrenal suppression"],
    monitoring: ["Peak flow", "Symptoms", "Oral examination", "Adrenal function"],
    conditions: ["Asthma", "Allergic rhinitis", "COPD", "Inflammation", "Allergies"]
  },
  {
    name: "Ciclesonide",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "80-320mcg daily",
    indications: ["Asthma", "Allergic rhinitis"],
    contraindications: ["Hypersensitivity", "Active tuberculosis", "Untreated fungal infection"],
    interactions: ["Ketoconazole", "Ritonavir", "Grapefruit juice"],
    sideEffects: ["Oral candidiasis", "Hoarseness", "Cough", "Adrenal suppression"],
    monitoring: ["Peak flow", "Symptoms", "Oral examination", "Adrenal function"],
    conditions: ["Asthma", "Allergic rhinitis", "Inflammation", "Allergies"]
  },
  {
    name: "Flunisolide",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "500-1000mcg daily in divided doses",
    indications: ["Asthma", "Allergic rhinitis"],
    contraindications: ["Hypersensitivity", "Active tuberculosis", "Untreated fungal infection"],
    interactions: ["Ketoconazole", "Ritonavir", "Grapefruit juice"],
    sideEffects: ["Oral candidiasis", "Hoarseness", "Cough", "Adrenal suppression"],
    monitoring: ["Peak flow", "Symptoms", "Oral examination", "Adrenal function"],
    conditions: ["Asthma", "Allergic rhinitis", "Inflammation", "Allergies"]
  },
  {
    name: "Triamcinolone Acetonide",
    category: "Anti-inflammatory",
    class: "Corticosteroid",
    dosage: "200-800mcg daily in divided doses",
    indications: ["Asthma", "Allergic rhinitis", "Skin conditions"],
    contraindications: ["Hypersensitivity", "Active tuberculosis", "Untreated fungal infection"],
    interactions: ["Ketoconazole", "Ritonavir", "Grapefruit juice"],
    sideEffects: ["Oral candidiasis", "Hoarseness", "Cough", "Adrenal suppression"],
    monitoring: ["Peak flow", "Symptoms", "Oral examination", "Adrenal function"],
    conditions: ["Asthma", "Allergic rhinitis", "Skin conditions", "Inflammation", "Allergies"]
  },

  // MUSCLE RELAXANTS (15+ drugs)
  {
    name: "Baclofen",
    category: "Muscle Relaxant",
    class: "GABA Agonist",
    dosage: "5-80mg daily in divided doses",
    indications: ["Muscle spasticity", "Multiple sclerosis", "Spinal cord injury"],
    contraindications: ["Stroke", "Cerebral palsy", "Parkinson's disease"],
    interactions: ["Alcohol", "Benzodiazepines", "Opioids", "Tricyclic antidepressants"],
    sideEffects: ["Drowsiness", "Dizziness", "Weakness", "Nausea"],
    monitoring: ["Muscle tone", "Functional ability", "Mental status"],
    conditions: ["Muscle spasticity", "Multiple sclerosis", "Spinal cord injury", "Muscle pain"]
  },
  {
    name: "Tizanidine",
    category: "Muscle Relaxant",
    class: "Alpha-2 Adrenergic Agonist",
    dosage: "2-36mg daily in divided doses",
    indications: ["Muscle spasticity", "Multiple sclerosis", "Spinal cord injury"],
    contraindications: ["Liver disease", "Concurrent use of CYP1A2 inhibitors"],
    interactions: ["Ciprofloxacin", "Fluvoxamine", "Oral contraceptives", "Alcohol"],
    sideEffects: ["Drowsiness", "Dizziness", "Dry mouth", "Weakness"],
    monitoring: ["Liver function", "Blood pressure", "Muscle tone"],
    conditions: ["Muscle spasticity", "Multiple sclerosis", "Spinal cord injury", "Muscle pain"]
  },
  {
    name: "Methocarbamol",
    category: "Muscle Relaxant",
    class: "Carbamate Derivative",
    dosage: "1500-4500mg daily in divided doses",
    indications: ["Acute muscle pain", "Muscle spasms", "Musculoskeletal conditions"],
    contraindications: ["Kidney disease", "Liver disease", "Pregnancy"],
    interactions: ["Alcohol", "Benzodiazepines", "Opioids", "Antihistamines"],
    sideEffects: ["Drowsiness", "Dizziness", "Nausea", "Blurred vision"],
    monitoring: ["Renal function", "Liver function", "Mental status"],
    conditions: ["Acute muscle pain", "Muscle spasms", "Musculoskeletal conditions", "Back pain"]
  },
  {
    name: "Cyclobenzaprine",
    category: "Muscle Relaxant",
    class: "Tricyclic Derivative",
    dosage: "5-10mg three times daily",
    indications: ["Muscle spasms", "Acute musculoskeletal pain"],
    contraindications: ["Heart failure", "Recent MI", "Hyperthyroidism", "MAO inhibitors"],
    interactions: ["MAO inhibitors", "Tramadol", "Alcohol", "Benzodiazepines"],
    sideEffects: ["Drowsiness", "Dry mouth", "Dizziness", "Blurred vision"],
    monitoring: ["Cardiac function", "Mental status", "Blood pressure"],
    conditions: ["Muscle spasms", "Acute musculoskeletal pain", "Back pain", "Neck pain"]
  },
  {
    name: "Carisoprodol",
    category: "Muscle Relaxant",
    class: "Carbamate Derivative",
    dosage: "250-350mg three times daily",
    indications: ["Acute musculoskeletal pain", "Muscle spasms"],
    contraindications: ["Porphyria", "Kidney disease", "Liver disease"],
    interactions: ["Alcohol", "Benzodiazepines", "Opioids", "Antihistamines"],
    sideEffects: ["Drowsiness", "Dizziness", "Headache", "Nausea"],
    monitoring: ["Mental status", "Liver function", "Renal function"],
    conditions: ["Acute musculoskeletal pain", "Muscle spasms", "Back pain", "Neck pain"]
  },
  {
    name: "Orphenadrine",
    category: "Muscle Relaxant",
    class: "Anticholinergic",
    dosage: "100mg twice daily",
    indications: ["Muscle spasms", "Musculoskeletal pain"],
    contraindications: ["Glaucoma", "Prostatic hypertrophy", "Myasthenia gravis"],
    interactions: ["Anticholinergics", "Alcohol", "Benzodiazepines", "Opioids"],
    sideEffects: ["Dry mouth", "Blurred vision", "Urinary retention", "Constipation"],
    monitoring: ["Eye pressure", "Urinary function", "Mental status"],
    conditions: ["Muscle spasms", "Musculoskeletal pain", "Back pain", "Neck pain"]
  },
  {
    name: "Chlorzoxazone",
    category: "Muscle Relaxant",
    class: "Benzoxazole Derivative",
    dosage: "250-750mg three times daily",
    indications: ["Muscle spasms", "Musculoskeletal pain"],
    contraindications: ["Liver disease", "Kidney disease", "Pregnancy"],
    interactions: ["Alcohol", "Benzodiazepines", "Opioids", "Antihistamines"],
    sideEffects: ["Drowsiness", "Dizziness", "Nausea", "Liver problems"],
    monitoring: ["Liver function", "Mental status", "Renal function"],
    conditions: ["Muscle spasms", "Musculoskeletal pain", "Back pain", "Neck pain"]
  },
  {
    name: "Metaxalone",
    category: "Muscle Relaxant",
    class: "Oxazolidinone Derivative",
    dosage: "800mg three times daily",
    indications: ["Muscle spasms", "Musculoskeletal pain"],
    contraindications: ["Liver disease", "Kidney disease", "Pregnancy"],
    interactions: ["Alcohol", "Benzodiazepines", "Opioids", "Antihistamines"],
    sideEffects: ["Drowsiness", "Dizziness", "Nausea", "Headache"],
    monitoring: ["Liver function", "Mental status", "Renal function"],
    conditions: ["Muscle spasms", "Musculoskeletal pain", "Back pain", "Neck pain"]
  },
  {
    name: "Dantrolene",
    category: "Muscle Relaxant",
    class: "Hydantoin Derivative",
    dosage: "25-100mg four times daily",
    indications: ["Muscle spasticity", "Malignant hyperthermia"],
    contraindications: ["Liver disease", "Pregnancy", "Lactation"],
    interactions: ["Alcohol", "Benzodiazepines", "Opioids", "Antihistamines"],
    sideEffects: ["Liver problems", "Drowsiness", "Dizziness", "Weakness"],
    monitoring: ["Liver function", "Mental status", "Muscle strength"],
    conditions: ["Muscle spasticity", "Malignant hyperthermia", "Muscle pain", "Spasticity"]
  },
  {
    name: "Pancuronium",
    category: "Muscle Relaxant",
    class: "Non-depolarizing Neuromuscular Blocker",
    dosage: "0.04-0.1mg/kg IV",
    indications: ["Surgical muscle relaxation", "Mechanical ventilation"],
    contraindications: ["Myasthenia gravis", "Severe kidney disease", "Severe liver disease"],
    interactions: ["Aminoglycosides", "Calcium channel blockers", "Beta blockers"],
    sideEffects: ["Respiratory depression", "Bradycardia", "Hypertension", "Prolonged paralysis"],
    monitoring: ["Respiratory function", "Heart rate", "Blood pressure", "Neuromuscular function"],
    conditions: ["Surgical muscle relaxation", "Mechanical ventilation", "Anesthesia"]
  },
  {
    name: "Vecuronium",
    category: "Muscle Relaxant",
    class: "Non-depolarizing Neuromuscular Blocker",
    dosage: "0.08-0.1mg/kg IV",
    indications: ["Surgical muscle relaxation", "Mechanical ventilation"],
    contraindications: ["Myasthenia gravis", "Severe kidney disease", "Severe liver disease"],
    interactions: ["Aminoglycosides", "Calcium channel blockers", "Beta blockers"],
    sideEffects: ["Respiratory depression", "Bradycardia", "Prolonged paralysis"],
    monitoring: ["Respiratory function", "Heart rate", "Neuromuscular function"],
    conditions: ["Surgical muscle relaxation", "Mechanical ventilation", "Anesthesia"]
  },
  {
    name: "Rocuronium",
    category: "Muscle Relaxant",
    class: "Non-depolarizing Neuromuscular Blocker",
    dosage: "0.6-1.2mg/kg IV",
    indications: ["Surgical muscle relaxation", "Rapid sequence intubation"],
    contraindications: ["Myasthenia gravis", "Severe kidney disease", "Severe liver disease"],
    interactions: ["Aminoglycosides", "Calcium channel blockers", "Beta blockers"],
    sideEffects: ["Respiratory depression", "Bradycardia", "Prolonged paralysis"],
    monitoring: ["Respiratory function", "Heart rate", "Neuromuscular function"],
    conditions: ["Surgical muscle relaxation", "Rapid sequence intubation", "Anesthesia"]
  },
  {
    name: "Succinylcholine",
    category: "Muscle Relaxant",
    class: "Depolarizing Neuromuscular Blocker",
    dosage: "0.5-1.5mg/kg IV",
    indications: ["Rapid sequence intubation", "Short surgical procedures"],
    contraindications: ["Myasthenia gravis", "Burns", "Trauma", "Hyperkalemia"],
    interactions: ["Aminoglycosides", "Calcium channel blockers", "Beta blockers"],
    sideEffects: ["Hyperkalemia", "Malignant hyperthermia", "Bradycardia", "Prolonged paralysis"],
    monitoring: ["Potassium levels", "Heart rate", "Neuromuscular function", "Temperature"],
    conditions: ["Rapid sequence intubation", "Short surgical procedures", "Emergency intubation"]
  },
  {
    name: "Cisatracurium",
    category: "Muscle Relaxant",
    class: "Non-depolarizing Neuromuscular Blocker",
    dosage: "0.1-0.2mg/kg IV",
    indications: ["Surgical muscle relaxation", "Mechanical ventilation"],
    contraindications: ["Myasthenia gravis", "Severe kidney disease", "Severe liver disease"],
    interactions: ["Aminoglycosides", "Calcium channel blockers", "Beta blockers"],
    sideEffects: ["Respiratory depression", "Bradycardia", "Prolonged paralysis"],
    monitoring: ["Respiratory function", "Heart rate", "Neuromuscular function"],
    conditions: ["Surgical muscle relaxation", "Mechanical ventilation", "Anesthesia"]
  },
  {
    name: "Atracurium",
    category: "Muscle Relaxant",
    class: "Non-depolarizing Neuromuscular Blocker",
    dosage: "0.3-0.6mg/kg IV",
    indications: ["Surgical muscle relaxation", "Mechanical ventilation"],
    contraindications: ["Myasthenia gravis", "Severe kidney disease", "Severe liver disease"],
    interactions: ["Aminoglycosides", "Calcium channel blockers", "Beta blockers"],
    sideEffects: ["Respiratory depression", "Bradycardia", "Histamine release", "Prolonged paralysis"],
    monitoring: ["Respiratory function", "Heart rate", "Blood pressure", "Neuromuscular function"],
    conditions: ["Surgical muscle relaxation", "Mechanical ventilation", "Anesthesia"]
  },

  // NEUROLOGICAL DRUGS (15+ drugs)
  {
    name: "Gabapentin",
    category: "Neurological",
    class: "Anticonvulsant",
    dosage: "300-3600mg daily in divided doses",
    indications: ["Neuropathic pain", "Postherpetic neuralgia", "Fibromyalgia"],
    contraindications: ["Severe kidney disease", "Hypersensitivity"],
    interactions: ["Morphine", "Antacids", "Alcohol", "Benzodiazepines"],
    sideEffects: ["Drowsiness", "Dizziness", "Peripheral edema", "Weight gain"],
    monitoring: ["Renal function", "Mental status", "Weight", "Edema"],
    conditions: ["Neuropathic pain", "Postherpetic neuralgia", "Fibromyalgia", "Epilepsy", "Anxiety"]
  },
  {
    name: "Pregabalin",
    category: "Neurological",
    class: "Anticonvulsant",
    dosage: "150-600mg daily in divided doses",
    indications: ["Neuropathic pain", "Fibromyalgia", "Generalized anxiety"],
    contraindications: ["Severe kidney disease", "Hypersensitivity"],
    interactions: ["Alcohol", "Benzodiazepines", "Opioids", "Antihistamines"],
    sideEffects: ["Drowsiness", "Dizziness", "Peripheral edema", "Weight gain"],
    monitoring: ["Renal function", "Mental status", "Weight", "Edema"],
    conditions: ["Neuropathic pain", "Fibromyalgia", "Generalized anxiety", "Epilepsy", "Chronic pain"]
  },
  {
    name: "Amitriptyline",
    category: "Neurological",
    class: "Tricyclic Antidepressant",
    dosage: "10-150mg daily (usually at night)",
    indications: ["Neuropathic pain", "Depression", "Migraine prevention"],
    contraindications: ["Recent MI", "Heart failure", "MAO inhibitors", "Pregnancy"],
    interactions: ["MAO inhibitors", "SSRIs", "Alcohol", "Benzodiazepines"],
    sideEffects: ["Drowsiness", "Dry mouth", "Constipation", "Weight gain"],
    monitoring: ["Cardiac function", "Mental status", "Blood pressure", "Weight"],
    conditions: ["Neuropathic pain", "Depression", "Migraine prevention", "Chronic pain", "Anxiety"]
  },
  {
    name: "Duloxetine",
    category: "Neurological",
    class: "SNRI",
    dosage: "30-120mg daily",
    indications: ["Depression", "Generalized anxiety", "Fibromyalgia", "Chronic pain"],
    contraindications: ["Liver disease", "Kidney disease", "MAO inhibitors", "Pregnancy"],
    interactions: ["MAO inhibitors", "SSRIs", "NSAIDs", "Warfarin"],
    sideEffects: ["Nausea", "Drowsiness", "Dizziness", "Dry mouth"],
    monitoring: ["Liver function", "Blood pressure", "Mental status"],
    conditions: ["Depression", "Generalized anxiety", "Fibromyalgia", "Chronic pain", "Neuropathic pain"]
  },
  {
    name: "Venlafaxine",
    category: "Neurological",
    class: "SNRI",
    dosage: "75-375mg daily in divided doses",
    indications: ["Depression", "Generalized anxiety", "Panic disorder"],
    contraindications: ["Severe kidney disease", "MAO inhibitors", "Pregnancy"],
    interactions: ["MAO inhibitors", "SSRIs", "NSAIDs", "Warfarin"],
    sideEffects: ["Nausea", "Drowsiness", "Hypertension", "Sexual dysfunction"],
    monitoring: ["Blood pressure", "Mental status", "Liver function"],
    conditions: ["Depression", "Generalized anxiety", "Panic disorder", "Social anxiety", "Chronic pain"]
  },
  {
    name: "Sertraline",
    category: "Neurological",
    class: "SSRI",
    dosage: "50-200mg daily",
    indications: ["Depression", "Generalized anxiety", "Panic disorder", "OCD"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "NSAIDs", "Warfarin", "Alcohol"],
    sideEffects: ["Nausea", "Insomnia", "Sexual dysfunction", "Weight changes"],
    monitoring: ["Mental status", "Liver function", "Blood pressure"],
    conditions: ["Depression", "Generalized anxiety", "Panic disorder", "OCD", "PTSD"]
  },
  {
    name: "Escitalopram",
    category: "Neurological",
    class: "SSRI",
    dosage: "10-20mg daily",
    indications: ["Depression", "Generalized anxiety", "Panic disorder"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "NSAIDs", "Warfarin", "Alcohol"],
    sideEffects: ["Nausea", "Insomnia", "Sexual dysfunction", "Weight changes"],
    monitoring: ["Mental status", "Liver function", "Blood pressure"],
    conditions: ["Depression", "Generalized anxiety", "Panic disorder", "Social anxiety"]
  },
  {
    name: "Fluoxetine",
    category: "Neurological",
    class: "SSRI",
    dosage: "20-80mg daily",
    indications: ["Depression", "OCD", "Bulimia nervosa", "Panic disorder"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "NSAIDs", "Warfarin", "Alcohol"],
    sideEffects: ["Nausea", "Insomnia", "Sexual dysfunction", "Weight changes"],
    monitoring: ["Mental status", "Liver function", "Blood pressure"],
    conditions: ["Depression", "OCD", "Bulimia nervosa", "Panic disorder", "PTSD"]
  },
  {
    name: "Paroxetine",
    category: "Neurological",
    class: "SSRI",
    dosage: "20-50mg daily",
    indications: ["Depression", "Generalized anxiety", "Panic disorder", "Social anxiety"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "NSAIDs", "Warfarin", "Alcohol"],
    sideEffects: ["Nausea", "Insomnia", "Sexual dysfunction", "Weight changes"],
    monitoring: ["Mental status", "Liver function", "Blood pressure"],
    conditions: ["Depression", "Generalized anxiety", "Panic disorder", "Social anxiety", "PTSD"]
  },
  {
    name: "Citalopram",
    category: "Neurological",
    class: "SSRI",
    dosage: "20-40mg daily",
    indications: ["Depression", "Generalized anxiety", "Panic disorder"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "NSAIDs", "Warfarin", "Alcohol"],
    sideEffects: ["Nausea", "Insomnia", "Sexual dysfunction", "Weight changes"],
    monitoring: ["Mental status", "Liver function", "Blood pressure", "ECG"],
    conditions: ["Depression", "Generalized anxiety", "Panic disorder", "Social anxiety"]
  },
  {
    name: "Bupropion",
    category: "Neurological",
    class: "NDRI",
    dosage: "150-450mg daily in divided doses",
    indications: ["Depression", "Seasonal affective disorder", "Smoking cessation"],
    contraindications: ["Seizure disorder", "Eating disorders", "MAO inhibitors"],
    interactions: ["MAO inhibitors", "Alcohol", "Antipsychotics", "Ritonavir"],
    sideEffects: ["Insomnia", "Headache", "Seizures", "Weight loss"],
    monitoring: ["Mental status", "Seizure activity", "Blood pressure"],
    conditions: ["Depression", "Seasonal affective disorder", "Smoking cessation", "ADHD"]
  },
  {
    name: "Mirtazapine",
    category: "Neurological",
    class: "Tetracyclic Antidepressant",
    dosage: "15-45mg daily",
    indications: ["Depression", "Insomnia", "Anxiety"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "Benzodiazepines", "Alcohol", "Warfarin"],
    sideEffects: ["Sedation", "Weight gain", "Increased appetite", "Dizziness"],
    monitoring: ["Mental status", "Weight", "Liver function", "Blood pressure"],
    conditions: ["Depression", "Insomnia", "Anxiety", "Chronic pain", "Nausea"]
  },
  {
    name: "Trazodone",
    category: "Neurological",
    class: "Serotonin Antagonist and Reuptake Inhibitor",
    dosage: "150-400mg daily in divided doses",
    indications: ["Depression", "Insomnia", "Anxiety"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "SSRIs", "Alcohol", "Warfarin"],
    sideEffects: ["Sedation", "Priapism", "Dizziness", "Nausea"],
    monitoring: ["Mental status", "Liver function", "Blood pressure", "Priapism"],
    conditions: ["Depression", "Insomnia", "Anxiety", "Chronic pain", "Sleep disorders"]
  },
  {
    name: "Vortioxetine",
    category: "Neurological",
    class: "Multimodal Antidepressant",
    dosage: "10-20mg daily",
    indications: ["Major depressive disorder", "Generalized anxiety"],
    contraindications: ["MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "SSRIs", "NSAIDs", "Warfarin"],
    sideEffects: ["Nausea", "Dizziness", "Insomnia", "Sexual dysfunction"],
    monitoring: ["Mental status", "Liver function", "Blood pressure"],
    conditions: ["Major depressive disorder", "Generalized anxiety", "Depression", "Anxiety"]
  },
  {
    name: "Agomelatine",
    category: "Neurological",
    class: "Melatonin Agonist and Serotonin Antagonist",
    dosage: "25-50mg daily",
    indications: ["Major depressive disorder"],
    contraindications: ["Liver disease", "MAO inhibitors", "Pregnancy", "Lactation"],
    interactions: ["MAO inhibitors", "Strong CYP1A2 inhibitors", "Alcohol"],
    sideEffects: ["Headache", "Dizziness", "Nausea", "Liver problems"],
    monitoring: ["Mental status", "Liver function", "Blood pressure"],
    conditions: ["Major depressive disorder", "Depression", "Mood disorders"]
  }
];
