module.exports = {
  ci: {
    collect: {
      url: ['http://localhost:3000'],
      numberOfRuns: 3,
    },
    assert: {
      assertions: {
        'categories:performance': ['error', { minScore: 0.9 }],
        'categories:accessibility': ['error', { minScore: 0.9 }],
        'categories:best-practices': ['error', { minScore: 0.9 }],
        'categories:seo': ['error', { minScore: 0.9 }],
        'first-contentful-paint': ['error', { maxNumericValue: 1800 }],
        'largest-contentful-paint': ['error', { maxNumericValue: 2500 }],
        'first-input-delay': ['error', { maxNumericValue: 100 }],
        'cumulative-layout-shift': ['error', { maxNumericValue: 0.1 }],
        'speed-index': ['error', { maxNumericValue: 3400 }],
        'total-blocking-time': ['error', { maxNumericValue: 200 }],
        'time-to-interactive': ['error', { maxNumericValue: 3800 }],
        'uses-optimized-images': 'error',
        'uses-webp-images': 'error',
        'uses-text-compression': 'error',
        'uses-responsive-images': 'error',
        'efficient-animated-content': 'error',
        'unused-css-rules': 'error',
        'unused-javascript': 'error',
        'modern-image-formats': 'error',
        'offscreen-images': 'error',
        'render-blocking-resources': 'error',
        'unminified-css': 'error',
        'unminified-javascript': 'error',
        'uses-long-cache-ttl': 'error',
        'uses-rel-preconnect': 'error',
        'uses-rel-preload': 'error',
        'font-display': 'error',
        'meta-description': 'error',
        'document-title': 'error',
        'link-text': 'error',
        'is-crawlable': 'error',
        'robots-txt': 'error',
        'canonical': 'error',
        'hreflang': 'error',
        'meta-viewport': 'error',
        'color-contrast': 'error',
        'image-alt': 'error',
        'label': 'error',
        'tabindex': 'error',
        'bypass': 'error',
        'focus-traps': 'error',
        'focusable-controls': 'error',
        'interactive-element-affordance': 'error',
        'logical-tab-order': 'error',
        'managed-focus': 'error',
        'offscreen-content-hidden': 'error',
        'use-landmarks': 'error',
        'visual-order-follows-dom': 'error',
        'uses-http2': 'error',
        'uses-passive-event-listeners': 'error',
        'no-document-write': 'error',
        'no-vulnerable-libraries': 'error',
        'notification-on-start': 'error',
        'password-inputs-can-be-pasted-into': 'error',
        'screenshot-thumbnails': 'error',
        'th-has-data-cells': 'error',
        'valid-source-maps': 'error',
        'video-caption': 'error',
        'video-description': 'error',
        'is-on-https': 'error',
        'csp-xss': 'error',
        'xss': 'error',
      },
    },
    upload: {
      target: 'temporary-public-storage',
    },
  },
};
